version:    '3'
services:
    frontend:
        build: frontend/
        ports: 
            - "80:8000"
    backend:
        build: backend/
        ports: 
            - "5000:5000"
    resources:
        build: resources/
        ports: 
            - "8282:8000"
    
    