apiVersion: v1
kind: Service
metadata:
  name: travelone-backend
  labels:
    app: travelone-backend
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: travelone-backend
    tier: backend