apiVersion: apps/v1 
kind: Deployment
metadata:
  name: travelone-frontend
  labels:
    app: travelone-frontend
spec:
  selector:
    matchLabels:
      app: travelone-frontend
#      role: master
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: travelone-frontend
#        role: master
        tier: frontend
    spec:
      containers:
      - name: travelone-frontend
        image: localhost:6000/travelone_frontend
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000

        livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2